version: '3'

services:
  app:
    build: .
    image: mohsenn
    ports:
      - "3000:3000"
    env_file:
      - .env  # This will load your .env file with the variables inside
    volumes:
      - .:/app
