
import type { Metadata } from "next";
// import { Signika_Negative } from "next/font/google";
import "./globals.css";
import MobileFooter from "./components/mobile-footer";
import HamburgerMenu from "./components/hamburger-menu";
import { Header } from "./components/header";
import { navItems } from "@/public/data";
import { ThemeProvider } from "./providers/theme-provider";
import Navbar from "./components/navbar";

// const SignikaNegative = Signika_Negative({
//   weight:["300","400","600","700"],
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
                <ThemeProvider attribute="class" defaultTheme="light">

        <Header navItems={navItems}/>

        <Navbar/>
        <MobileFooter/>
        {children}
        </ThemeProvider>

      </body>
    </html>
  );
}
